######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 17 17:22:54 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
